### ISSUE TITLE
Crash when setting autopilot.local_pos

### ISSUE THREAD

**Issue by GoCyberEd** [pennaerial/pennair2#23]
The library crashes when running the takeoff script in the src/test folder. The stacktrace is below.

    pennair@pennair-eddie:~/catkin_ws/src/pennair2/src/test$ python takeoff.py 
    [INFO] [1520042394.982927]: Waiting for autopilot connection.
    [INFO] [1520042394.984817]: Connected.
    [INFO] [1520042394.987222]: Waiting for arm.
    [INFO] [1520042399.429630]: Waiting for offboard.
    Exception in thread Thread-18:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 223, in run
        self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
      File "/home/pennair/catkin_ws/src/pennair2/src/pennair2/core.py", line 53, in __control_loop
        self.autopilot.local_pose = self._setpoint_pos
      File "/home/pennair/catkin_ws/src/pennair2/src/pennair2/autopilot.py", line 128, in local_pose
        self._local_pose_setter(val)
      File "/home/pennair/catkin_ws/src/pennair2/src/pennair2/autopilot.py", line 299, in _local_pose_setter
        self.position_pub.publish(msg)
      File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 886, in publish
        raise ROSSerializationException(str(e))
    ROSSerializationException: field header.frame_id must be of type str`

**Comment by GoCyberEd** [comment]
This is an issue with the line: 

    quad.land()
